homework-5
KatyaKlema/android-course pull request #5
Opened 2020-11-09 13:51 UTC by KatyaKlema

2020-11-12 13:51 UTC, IvanShafran commented
@KatyaKlema появились конфликты после merge-а 4-го ДЗ. Нужно поправить

2020-11-12 14:32 UTC, KatyaKlema commented
Конфликты исправила

2020-11-14 16:48 UTC, IvanShafran requested changes
Хорошо, но есть над чем поработать в этом PR. Глянь комментарии, пожалуйста

2020-11-14 16:48 UTC, IvanShafran commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".Article2"/>
Лишний код? Убери, пожалуйста, все Article0 и подобные файлы из кода

2020-11-14 16:48 UTC, IvanShafran commented on app/src/main/java/com/example/notes/Article0.kt
> +package com.example.notes
В репозиторий .DS_Store файлы добавились. Стоит убрать
Нужно их удалить и добавить в .gitignore глобально, если система генерирует их

2020-11-14 16:48 UTC, IvanShafran commented on app/src/main/java/com/example/notes/MainActivity.kt
> +    class Article(text_ : String, date_ : String,  photoId_ : Int, activity_ : AppCompatActivity, articleId_ : Int) {
1. Такие классы лучше выделять отдельно, а не в рамках MainActivity.
- Article -- сущность логическая и необязательно привязана к Activity, а тем более конкретной
Например, в 7-ом ДЗ Article будет из базы данных доставаться
2. activity_ -- Держать ссылку на Context, Activity, Fragment в рамках Data сущности обычно плохо. Можно попасться на утечках памяти.

2020-11-14 16:48 UTC, IvanShafran commented on app/src/main/java/com/example/notes/MainActivity.kt
> +        var text : String = text_
Можно заменить var text: String = text_ на 
class Article(var text: String) -- это равносильно в Kotlin
Т.е. весь класс можно представить class Article(val text: String, val photoId: Int, ...)
val -- если значения не нужно менять позже

2020-11-14 16:48 UTC, IvanShafran commented on app/src/main/java/com/example/notes/MainActivity.kt
> +        var articleId : Int =  articleId_
Если брать стандартные codestyle, то пробелов перед : тут не нужно. Но если везде будешь одного своего codestyle придерживаться, то я не против.
Если хочешь стандартный Kotlin, то  CTRL+ALT+L on Windows or Command+Option+L on Mac

2020-11-16 13:03 UTC, KatyaKlema commented
Сделала теперь по-нормальному

2020-11-21 20:46 UTC, IvanShafran approved these changes

2020-11-21 20:46 UTC, IvanShafran commented on app/src/main/java/com/example/notes/Article.kt
> +class Article(var text: String, var date: String, var photoId: Int, var articleId: Int) {
Фигурные скобки можно убрать

2020-11-21 20:46 UTC, merged